Glancing Blow DMG and chance
BreakBB/ExtendedCharacterStats pull request #305
Opened 2024-03-08 17:08 UTC by Norderud

#10 
Added  glancing blow chance and damage in the melee section.
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/36229766/07b99ec4-0f11-4322-a1de-0313e024a933)

Used ChatGPT for translations, not able to confirm if correct or not.

2024-03-09 23:21 UTC, anon1231823 commented
Is glancing blow a community created term? Or does Blizzard use this name in like wowhead that can be searched?

2024-03-13 06:58 UTC, BreakBB requested changes
Hey @puggan 

first of all: Thank you very much for looking into adding these stats to ECS! I really appreciate any help I get on this project.

I left a few comments and suggestions in the code itself. On top of that, the calculation for Glancing Blows which you added, is the one for Era/HC/SoD, therefore these values should be hidden for everything else.

The settings can be hidden by adding the `hidden` field:
```lua
                        hidden = function()
                            return (not ECS.IsClassic)
                        end,
```

To not add the values itself, checkout `Stats.lua` -> `_CreateStatInfos` in which we already use `ECS.IsWotlk` to hide specific stats on non-WotLK clients. You can adjust these to also check for `ECS.IsClassic` to then conditionally add the Glancing Blow stats.

Let me know if you want to tackle these, otherwise I'll look into adjusting the PR to get it out and released 💪🏻

2024-03-13 06:58 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        desc = function() return i18n("Shows/Hides the melee miss chance against enemies on the same level.") end,
```suggestion
                        desc = function() return i18n("Shows/Hides the glancing chance against enemies on same level.") end,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        desc = function() return i18n("Shows/Hides the melee miss chance against boss enemies (+3 Level).") end,
```suggestion
                        desc = function() return i18n("Shows/Hides the glancing chance against boss enemies (+3 Level).") end,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/Data/Melee.lua
> +    glancePenalty = DataUtils:GetGlancingDamage(mainBase + mainMod, enemyDefenseValue)
```suggestion
    local glancePenalty = DataUtils:GetGlancingDamage(mainBase + mainMod, enemyDefenseValue)
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        name = function() return i18n("Glancing Blow Damage") end,
```suggestion
                        name = function() return i18n("Glancing Blow Damage Boss") end,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        desc = function() return i18n("Shows/Hides the glancing dmg mod % against enemies on the same level.") end,
This does not match the wording in `MeleeConfigTranslations.lua`. How about:

> Shows/Hides the damage reduction against enemies on the same level.

2024-03-13 06:58 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        desc = function() return i18n("Shows/Hides the glancing dmg mod % against enemies on the same level.") end,
Same as with the other, the wording does not match. Maybe this fits better:

> Shows/Hides the damage reduction against enemies on boss level (+3 Level).

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Glancing Blow Chance",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Shows/Hides the glancing chance against enemies on same level.",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Glancing Blow Chance Boss",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Shows/Hides the glancing chance against boss enemies (+3 Level).",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Glancing Blow Damage",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +    },
These needs to be updated as well, after the translation is changed.

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +    },
Same as with the other.

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Glancing Blow Damage Boss",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Melee Glance Values",
```suggestion
        ["enUS"] = true,
```

2024-03-13 06:58 UTC, BreakBB commented on Modules/i18n/translations/ConfigTranslations/MeleeConfigTranslations.lua
> +        ["enUS"] = "Shows/Hides all glancing blow stats",
```suggestion
        ["enUS"] = true,
```

2024-03-18 19:03 UTC, BreakBB commented
Sounds good @Norderud ! Let me know, when you are done or if you need further help/ideas 👍🏻

2024-03-19 14:31 UTC, BreakBB requested changes

2024-03-19 14:31 UTC, BreakBB commented on Modules/Config/MeleeSection.lua
> +                        desc = function() return i18n("Shows/Hides the damage reduction against enemies on the same level.") end,
The translation does not match with this. I like the wording though and think it should be the same for `meleeGlanceDamageBoss` a few lines below

2024-03-26 13:19 UTC, BreakBB approved these changes

2024-03-26 13:20 UTC, BreakBB commented
Thank you @Norderud for continuing to work on this! Looking good to me. I'll see to ship it in a release very soon.

2024-03-26 13:26 UTC, merged